# Generated by Django 4.2.7 on 2024-03-16 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_options_rename_created_at_order_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
    ]
