# Generated by Django 4.2.7 on 2024-03-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slip", models.ImageField(upload_to="payment_slips/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_slip",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
