# Generated by Django 4.2.7 on 2024-03-16 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
