# Generated by Django 4.2.7 on 2024-03-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("V", "Verified"), ("C", "Completed")],
                default="P",
                max_length=1,
            ),
        ),
    ]
